### ISSUE TITLE
I would like to be able to delete the resource at point

### ISSUE THREAD

**Issue by eval-on-point** [jinnovation/kele.el#194]
This is one of the main features I use in k9s that appears to be absent in kele. Similar to #157, I think it would be nice to be able to put my point on a resource and delete it. Just spitballing, this could be achieved with a magit like map which binds `k` when in a kele buffer or as an embark action.

**Comment by jinnovation** [comment]
This is a great idea.

> Just spitballing, this could be achieved with a magit like map which binds k when in a kele buffer or as an embark action.

Always appreciate UX suggestions. (:

I'm not investing much in Embark integration at the moment in favor of built-ins (see closing comment on #28 and others). What I've done in #195, though, I think fits your first suggestion pretty well; I've added a `k` keybinding to `kele-list` that deletes the resource at point.
